# -*- coding: utf-8 -*-
"""removeSquirrels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R6EyWJdEnAAqZYfTZK1pT6WACIH5fetb
"""

from PIL import Image
import requests
import torch
from io import BytesIO
from diffusers import StableDiffusionInpaintPipeline
import tensorflow as tf

image_paths = [
    "squirrels/squirrelFeeder 6.jpg",
    "squirrels/squirrelFeeder 7.jpg",
    "squirrels/squirrelFeeder 1.jpg",
    "squirrels/squirrelFeeder 2.jpg",
    "squirrels/squirrelFeeder 5.jpg",
]

image_names = [
    "squirrelFeeder 6.jpg",
    "squirrelFeeder 7.jpg",
    "squirrelFeeder 1.jpg",
    "squirrelFeeder 2.jpg",
    "squirrelFeeder 5.jpg",
]

mask_paths = [
    "squirrelMasks/mask_squirrelFeeder 6.jpg",
    "squirrelMasks/mask_squirrelFeeder 7.jpg",
    "squirrelMasks/mask_squirrelFeeder 1.jpg",
    "squirrelMasks/mask_squirrelFeeder 2.jpg",
    "squirrelMasks/mask_squirrelFeeder 5.jpg",
]

pipeline = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting"
)

pipeline = pipeline.to('cuda')
# Perform inpainting on each image
for i in range(len(image_paths)):
    image_path = image_paths[i]
    mask_path = mask_paths[i]
    image_names = image_names[i]
    init_image = Image.open(image_path).resize((512, 512))
    mask_image = Image.open(mask_path).resize((512, 512))
    prompt = 'Grass field. high resolution'
    inpainted_image = pipeline(prompt=prompt, image=init_image, mask_image=mask_image).images[0]

    output_filename = image_names.replace(".jpg", "-squirrelsRemoved.jpg")
    inpainted_image.save(output_filename)