# -*- coding: utf-8 -*-
"""replaceBirds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QoCNabZFY0PnZXTRb9z2yLAPfgBOM12O
"""

from PIL import Image
import requests
import torch
from io import BytesIO
from diffusers import StableDiffusionInpaintPipeline
import tensorflow as tf

image_paths = [
    "birds/birder 1.jpg",
    "birds/birder 2.jpg",
    "birds/birder 3.jpg",
    "birds/birder 4.jpg",
    "birds/birder 5.jpg",
]

image_names = [
    "birder 1.jpg",
    "birder 2.jpg",
    "birder 3.jpg",
    "birder 4.jpg",
    "birder 5.jpg",
]

mask_paths = [
    "birdMasks/mask_birder 1.jpg",
    "birdMasks/mask_birder 2.jpg",
    "birdMasks/mask_birder 3.jpg",
    "birdMasks/mask_birder 4.jpg",
    "birdMasks/mask_birder 5.jpg",
]

pipeline = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting"
)

pipeline = pipeline.to('cuda')
# Perform inpainting on each image
for i in range(len(image_paths)):
    image_path = image_paths[i]
    mask_path = mask_paths[i]
    init_image = Image.open(image_path).resize((512, 512))
    mask_image = Image.open(mask_path).resize((512, 512))
    prompt = 'Bird replaced with an exotic bird, high resolution'
    inpainted_image = pipeline(prompt=prompt, image=init_image, mask_image=mask_image).images[0]

    output_filename = image_names.replace(".jpg", "-andBirdsReplaced.jpg")
    inpainted_image.save(output_filename)