# -*- coding: utf-8 -*-
"""createSavedDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Vha0i91eMTKBs1Z00M8FO9n5Eyiy6FB
"""

from google.colab import drive 
drive.mount('/content/gdrive')

#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import urllib.request

import tensorflow as tf
from tensorflow.train import BytesList,FloatList,Int64List
from tensorflow.train import Feature,Features,Example

inData = pd.read_pickle('/content/gdrive/MyDrive/Applied ML/Assignment 1/appml-assignment1-dataset-v2.pkl')

X=inData['X']
y=inData['y']
fracDiff = (X['CAD-high']-X['CAD-close'])/X['CAD-close']
bin21 = np.linspace(-0.001,0.001,num=21)

print(bin21)

bins = [-1.e-03, -9.e-04, -8.e-04, -7.e-04, -6.e-04, -5.e-04, -4.e-04, -3.e-04, -2.e-04,
 -1.e-04,  0.e+00,  1.e-04,  2.e-04,  3.e-04,  4.e-04,  5.e-04,  6.e-04,  7.e-04,
  8.e-04,  9.e-04,  1.e-03]

X['target']=np.digitize(fracDiff,bins,right=False)

print(X['target'])

print(X)

print(y)

X['weekday'] = X['date'].dt.dayofweek
X['hour'] = X['date'].dt.hour
X['month'] = X['date'].dt.month-1

print(X['weekday'].value_counts())

num_cols = X.columns[1:-4]



with tf.io.TFRecordWriter('MLAssignment1.tfrecord') as f:
    for row in X.iterrows():
        myDict={'tickers':Feature(float_list=FloatList(value=row[1][num_cols].to_numpy())),
                'weekday':Feature(int64_list=Int64List(value=[row[1]['weekday']])),
                'hour':Feature(int64_list=Int64List(value=[row[1]['hour']])),
                'month':Feature(int64_list=Int64List(value=[row[1]['month']])),
                'target':Feature(int64_list=Int64List(value=[row[1]['target']]))}
        myExamp=Example(features=Features(feature=myDict))
        f.write(myExamp.SerializeToString())

#Accesing my tfrecords file
filepaths = ['/content/MLAssignment1.tfrecord']
dataset = tf.data.TFRecordDataset(filepaths)
for item in dataset:
  print(item)

#compare my model to the correct model that is there
filepaths = ['/content/gdrive/MyDrive/Applied ML/Assignment 1/correct.tfrecord']
dataset = tf.data.TFRecordDataset(filepaths)
for item in dataset:
  print(item)